openapi: 3.0.3
info:
  title: 'Abyss Tracker Conduit'
  description: 'An API interface for the Abyss Tracker'
  version: 1.0.0
servers:
  -
    url: 'https://abyss.eve-nt.uk'
paths:
  /api/conduit/v1/fits/list:
    get:
      summary: 'List fits'
      description: 'Lists all fits selectable by the authenticated user: public fits, incognito fits, and users'' private fits. Cached for a minute.'
      parameters:
        -
          in: query
          name: flexibleFitHash
          description: 'Fit hash to match (full match, lowercase, see https://github.com/molbal/abyss-tracker/wiki/Flexible-Fit-Hash)'
          example: e892eac7e0c39ec6cb683211aed4f40a
          required: false
          schema:
            type: string
            description: 'Fit hash to match (full match, lowercase, see https://github.com/molbal/abyss-tracker/wiki/Flexible-Fit-Hash)'
            example: e892eac7e0c39ec6cb683211aed4f40a
        -
          in: query
          name: revisions
          description: 'If provided, only fits with historical relation to this will be displayed.'
          example: 76
          required: false
          schema:
            type: integer
            description: 'If provided, only fits with historical relation to this will be displayed.'
            example: 76
        -
          in: query
          name: mineOnly
          description: 'If provided, only the authenticated user''s fits will be returned. If false, or not set, only public fits will be returned.'
          example: true
          required: false
          schema:
            type: boolean
            description: 'If provided, only the authenticated user''s fits will be returned. If false, or not set, only public fits will be returned.'
            example: true
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: '200'
          content:
            application/json:
              schema:
                type: object
                example:
                  success: true
                  char:
                    id: 93940047
                    name: 'Veetor Nara'
                  items:
                    -
                      id: 157
                      name: Example
                      uploader:
                        privacy: public
                        char:
                          id: 93940047
                          name: 'Veetor Nara'
                      ship:
                        id: 629
                        name: Rupture
                        size: cruiser
                  count: 1
                  error: null
                properties:
                  success:
                    type: boolean
                    example: true
                    description: 'true on normal operation, false on exception'
                  char:
                    type: object
                    example:
                      id: 93940047
                      name: 'Veetor Nara'
                    description: 'contains the authenticated character''s ID and name'
                  items:
                    type: array
                    example:
                      -
                        id: 157
                        name: Example
                        uploader:
                          privacy: public
                          char:
                            id: 93940047
                            name: 'Veetor Nara'
                        ship:
                          id: 629
                          name: Rupture
                          size: cruiser
                    description: 'array contains the fits'' short forms'
                    items:
                      type: object
                  count:
                    type: integer
                    example: 1
                    description: 'contains how many records were returned'
                  error:
                    type: string
                    example: null
                    description: 'null on normal operation, string containing error message on exception'
      tags:
        - Fits
  '/api/conduit/v1/fits/get/{id}':
    get:
      summary: 'Get a single fit'
      description: 'Gets most data for a fit. Cached for a minute.'
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: '200'
          content:
            application/json:
              schema:
                type: object
                example:
                  success: true
                  char:
                    id: 93940047
                    name: 'Veetor Nara'
                  item:
                    id: 76
                    name: 'Easy passive Gila'
                    uploader:
                      privacy: public
                      char:
                        id: 93940047
                        name: 'Veetor Nara'
                    ship:
                      id: 17715
                      name: Gila
                      size: cruiser
                    eft: "[Gila, Easy passive Gila]\r\n\r\nDrone Damage Amplifier II\r\nDrone Damage Amplifier II\r\nDrone Damage Amplifier II\r\n\r\nCaldari Navy Large Shield Extender\r\nCaldari Navy Large Shield Extender\r\nCaldari Navy Large Shield Extender\r\nAdaptive Invulnerability Shield Hardener II\r\nAdaptive Invulnerability Shield Hardener II\r\nFederation Navy 10MN Afterburner\r\n\r\nRapid Light Missile Launcher II, Caldari Navy Nova Light Missile\r\nRapid Light Missile Launcher II, Caldari Navy Nova Light Missile\r\nRapid Light Missile Launcher II, Caldari Navy Nova Light Missile\r\nRapid Light Missile Launcher II, Caldari Navy Nova Light Missile\r\nMedium Ghoul Compact Energy Nosferatu\r\n\r\nMedium Core Defense Field Purger II\r\nMedium Core Defense Field Purger II\r\nMedium Core Defense Field Purger II\r\n\r\n\r\nRepublic Fleet Valkyrie x2\r\nRepublic Fleet Valkyrie x2\r\nValkyrie II x2\r\nValkyrie II x2\r\nValkyrie II x2"
                    flexibleFitHash: e892eac7e0c39ec6cb683211aed4f40a
                    tags:
                      - Afterburner
                      - 'Strong drones'
                      - Missiles
                      - 'Shield regen tank'
                    stats:
                      offense:
                        totalDps: '566.9'
                        weaponDps: '121.62'
                        droneDps: '445.28'
                        totalVolley: '2303.62'
                      defense:
                        ehp:
                          total: '51801.874919544'
                          shield: '43082.278457411'
                          armor: '4074.0740740741'
                          hull: '4645.5223880597'
                        resists:
                          shield:
                            em: '0.5418'
                            therm: '0.6334'
                            kin: '0.7251'
                            exp: '0.7709'
                          armor:
                            em: '0.5'
                            therm: '0.45'
                            kin: '0.25'
                            exp: '0.1'
                          hull:
                            em: '0.33'
                            therm: '0.33'
                            kin: '0.33'
                            exp: '0.33'
                        reps:
                          burst:
                            shieldRegen: '272.32'
                            shieldBoost: '0'
                            armor: '0'
                            hull: '0'
                            total: '272.32'
                          sustained:
                            shieldRegen: '272.32'
                            shieldBoost: '0'
                            armor: '0'
                            hull: '0'
                            total: '272.32'
                      misc:
                        ship:
                          id: '17715'
                          name: Gila
                          cpuMax: '475'
                          powerMax: '837.5'
                          cpuUsed: '448'
                          pgUsed: '829.7'
                          calibrationUsed: '225'
                          warpSpeed: '4'
                        drones:
                          activeDrones: '2'
                          droneBayTotal: '100'
                          droneBandwidthUsed: '20'
                          droneBayUsed: '20'
                        maxSpeed: '697.65'
                        signature: '247.91'
                        capacitor:
                          capacity: '1750'
                          stable: '1'
                          stableAt: '90.48'
                        targeting:
                          range: '72500'
                          resolution: '356.25'
                          strength: '26.4'
                    status: works
                    price: 462898985
                  error: null
                properties:
                  success:
                    type: boolean
                    example: true
                    description: 'true on normal operation, false on exception'
                  char:
                    type: object
                    example:
                      id: 93940047
                      name: 'Veetor Nara'
                    description: 'contains the authenticated character''s ID and name'
                  item:
                    type: object
                    example:
                      id: 76
                      name: 'Easy passive Gila'
                      uploader:
                        privacy: public
                        char:
                          id: 93940047
                          name: 'Veetor Nara'
                      ship:
                        id: 17715
                        name: Gila
                        size: cruiser
                      eft: "[Gila, Easy passive Gila]\r\n\r\nDrone Damage Amplifier II\r\nDrone Damage Amplifier II\r\nDrone Damage Amplifier II\r\n\r\nCaldari Navy Large Shield Extender\r\nCaldari Navy Large Shield Extender\r\nCaldari Navy Large Shield Extender\r\nAdaptive Invulnerability Shield Hardener II\r\nAdaptive Invulnerability Shield Hardener II\r\nFederation Navy 10MN Afterburner\r\n\r\nRapid Light Missile Launcher II, Caldari Navy Nova Light Missile\r\nRapid Light Missile Launcher II, Caldari Navy Nova Light Missile\r\nRapid Light Missile Launcher II, Caldari Navy Nova Light Missile\r\nRapid Light Missile Launcher II, Caldari Navy Nova Light Missile\r\nMedium Ghoul Compact Energy Nosferatu\r\n\r\nMedium Core Defense Field Purger II\r\nMedium Core Defense Field Purger II\r\nMedium Core Defense Field Purger II\r\n\r\n\r\nRepublic Fleet Valkyrie x2\r\nRepublic Fleet Valkyrie x2\r\nValkyrie II x2\r\nValkyrie II x2\r\nValkyrie II x2"
                      flexibleFitHash: e892eac7e0c39ec6cb683211aed4f40a
                      tags:
                        - Afterburner
                        - 'Strong drones'
                        - Missiles
                        - 'Shield regen tank'
                      stats:
                        offense:
                          totalDps: '566.9'
                          weaponDps: '121.62'
                          droneDps: '445.28'
                          totalVolley: '2303.62'
                        defense:
                          ehp:
                            total: '51801.874919544'
                            shield: '43082.278457411'
                            armor: '4074.0740740741'
                            hull: '4645.5223880597'
                          resists:
                            shield:
                              em: '0.5418'
                              therm: '0.6334'
                              kin: '0.7251'
                              exp: '0.7709'
                            armor:
                              em: '0.5'
                              therm: '0.45'
                              kin: '0.25'
                              exp: '0.1'
                            hull:
                              em: '0.33'
                              therm: '0.33'
                              kin: '0.33'
                              exp: '0.33'
                          reps:
                            burst:
                              shieldRegen: '272.32'
                              shieldBoost: '0'
                              armor: '0'
                              hull: '0'
                              total: '272.32'
                            sustained:
                              shieldRegen: '272.32'
                              shieldBoost: '0'
                              armor: '0'
                              hull: '0'
                              total: '272.32'
                        misc:
                          ship:
                            id: '17715'
                            name: Gila
                            cpuMax: '475'
                            powerMax: '837.5'
                            cpuUsed: '448'
                            pgUsed: '829.7'
                            calibrationUsed: '225'
                            warpSpeed: '4'
                          drones:
                            activeDrones: '2'
                            droneBayTotal: '100'
                            droneBandwidthUsed: '20'
                            droneBayUsed: '20'
                          maxSpeed: '697.65'
                          signature: '247.91'
                          capacitor:
                            capacity: '1750'
                            stable: '1'
                            stableAt: '90.48'
                          targeting:
                            range: '72500'
                            resolution: '356.25'
                            strength: '26.4'
                      status: works
                      price: 462898985
                    description: 'contains the fit''s extended form'
                  error:
                    type: string
                    example: null
                    description: 'null on normal operation, string containing error message on exception'
      tags:
        - Fits
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the get.'
        example: similique
        required: true
        schema:
          type: string
  /api/conduit/v1/ping:
    get:
      summary: 'Ping endpoint'
      description: 'Returns a single success=>true endpoint if the auth token is valid.'
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: '200'
          content:
            application/json:
              schema:
                type: object
                example:
                  success: true
                  char:
                    id: 93940047
                    name: 'Veetor Nara'
                properties:
                  success:
                    type: boolean
                    example: true
                  char:
                    type: object
                    example:
                      id: 93940047
                      name: 'Veetor Nara'
                    description: 'contains the authenticated character''s ID and name'
      tags:
        - Misc
components:
  securitySchemes:
    default:
      type: http
      scheme: bearer
      description: ''
security:
  -
    default: []
